name: Create Pull Request

on:
  push:
    branches:
      - dev
      - prod
      - uat

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MAIN_TOKEN }}
          branch: ${{ github.ref }}
          title: Automated PR from ${{ github.ref }}
          body: |
            This is an automated PR created from the ${{ github.ref }} branch.
