name: Set Variables and Trigger Main Workflow

on:
  workflow_dispatch:

jobs:
  set-variables-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        run: |
          echo "DOMAIN_NAME=dev" >> $GITHUB_ENV
          echo "BUCKET_NAME=newest-hre" >> $GITHUB_ENV
          echo "FOLDER_NAME=dev" >> $GITHUB_ENV
          echo "DOMAIN_NAME=${DOMAIN_NAME}"
          echo "BUCKET_NAME=${BUCKET_NAME}"
          echo "FOLDER_NAME=${FOLDER_NAME}"
